import { GoogleGenAI } from '@google/genai';
import { AppraisalSchema, SuccessResponseSchema } from './schema';
import { groundMarket } from './market';

export class AppraisalError extends Error { constructor(message: string, public code: string, public statusCode: number, public details?: unknown) { super(message); this.name = 'AppraisalError'; } }
export const MAX_IMAGE_BYTES = 15 * 1024 * 1024;
export const GEMINI_MODEL = 'models/gemini-3.6-flash';
const PROMPT = `You are PriceSnap Vision. Return ONLY JSON: {"item":string|null,"item_category":string|null,"item_name":string|null,"brand":string|null,"condition_score":number|null,"defects":string[],"confidence":number|null}. Confidence is 0..1. Never invent identity, condition, confidence or price. Do not estimate marketplace prices. Use null identity fields when uncertain.`;

export function parseImageInput(body: unknown) {
  const input = (body as any)?.imageBase64 ?? (body as any)?.image;
  if (typeof input !== 'string' || !input.trim()) throw new AppraisalError('A base64 image data URL is required.', 'NO_IMAGE', 400);
  const match = input.match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=\r\n]+)$/);
  if (!match) throw new AppraisalError('Only JPEG, PNG and WebP base64 data URLs are supported.', 'UNSUPPORTED_IMAGE', 415);
  const base64Data = match[2].replace(/\s/g, ''); const bytes = Buffer.from(base64Data, 'base64');
  if (!bytes.length) throw new AppraisalError('Image payload is empty.', 'INVALID_IMAGE', 400);
  if (bytes.length > MAX_IMAGE_BYTES) throw new AppraisalError('Image exceeds the 15 MB decoded image limit.', 'IMAGE_TOO_LARGE', 413);
  const mimeType = match[1];
  const valid = mimeType === 'image/jpeg' ? bytes[0] === 0xff && bytes[1] === 0xd8 : mimeType === 'image/png' ? bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])) : bytes.subarray(0,4).toString('ascii') === 'RIFF' && bytes.subarray(8,12).toString('ascii') === 'WEBP';
  if (!valid) throw new AppraisalError('Declared image MIME type does not match the file signature.', 'MIME_MISMATCH', 415);
  return { mimeType, base64Data };
}
export function sanitizeAndParseJson(raw: string): any { if (!raw) throw new AppraisalError('Empty response from appraisal model.', 'EMPTY_MODEL_RESPONSE', 502); const clean = raw.replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/```(?:json)?/gi,'').replace(/```/g,'').trim(); const a=clean.indexOf('{'), b=clean.lastIndexOf('}'); if(a<0||b<a) throw new AppraisalError('Model response did not contain JSON.','INVALID_MODEL_JSON',502); try{return JSON.parse(clean.slice(a,b+1));}catch{throw new AppraisalError('Model returned malformed JSON.','INVALID_MODEL_JSON',502);} }
const num=(v:unknown)=>v===null||v===undefined||v===''?null:Number.isFinite(Number(v))?Number(v):null;
export function normalizeVision(data:any){ let confidence=num(data?.confidence); if(confidence!==null&&confidence>1&&confidence<=100)confidence/=100; confidence=confidence===null?null:Math.max(0,Math.min(1,confidence)); const raw=data?.item??data?.item_name??null; const unidentified=typeof raw!=='string'||!raw.trim()||(confidence!==null&&confidence<.3); const s=num(data?.condition_score); const score=s===null?null:Math.max(1,Math.min(10,s)); const defects=Array.isArray(data?.defects)?data.defects.filter((x:unknown):x is string=>typeof x==='string'):[]; return unidentified?{status:'unidentified' as const,name:null,category:null,brand:null,score:null,defects:[],confidence}:{status:'identified' as const,name:raw.trim(),category:typeof data?.item_category==='string'?data.item_category:null,brand:typeof data?.brand==='string'?data.brand:null,score,defects,confidence}; }
const grade=(s:number|null)=>s===null?null:s>=9?'Mint':s>=7?'Great':s>=5?'Good':'Fair';
export async function analyzeAppraisal(body:unknown, requestId=crypto.randomUUID()) { const started=Date.now(); const {base64Data,mimeType}=parseImageInput(body); const apiKey=process.env.GOOGLE_AI_STUDIO_API_KEY||process.env.GEMINI_API_KEY; if(!apiKey)throw new AppraisalError('Gemini API key is not configured.','AI_NOT_CONFIGURED',503); let response:any; try{response=await new GoogleGenAI({apiKey}).models.generateContent({model:GEMINI_MODEL,contents:[{role:'user',parts:[{inlineData:{data:base64Data,mimeType}},{text:PROMPT}]}]});}catch(e:any){throw new AppraisalError(e?.message||'Appraisal model request failed.','AI_STUDIO_UNREACHABLE',502);} const vision=normalizeVision(sanitizeAndParseJson(response.text||response?.response?.text?.()||'')); const grounding=vision.status==='identified'&&vision.name?await groundMarket(vision.name):{market:null,durationMs:0,warnings:[]}; const price=grounding.market?.recommended_price??null; const appraisal=AppraisalSchema.parse({status:vision.status,item:vision.name,item_category:vision.category,item_name:vision.name,brand:vision.brand,conditionScore:vision.score,condition_score:vision.score,defects:vision.defects,resale_price_nz:price,confidence:vision.confidence,market:grounding.market,product:{name:vision.name,brand:vision.brand,category:vision.category,condition_score:vision.score,condition_grade:grade(vision.score),defects:vision.defects,resale_price_nz:price,confidence:vision.confidence,confidence_color:vision.confidence!==null&&vision.confidence>=.85?'green':vision.confidence!==null&&vision.confidence>=.6?'orange':'red',summary:vision.status==='identified'?(grounding.market?.grounded?'AI identification with price derived from retrieved marketplace evidence.':'AI identification complete. No marketplace evidence was available, so no price was invented.'):'Item could not be identified reliably. Try a clearer photo.'}}); const timestamp=new Date().toISOString(); return SuccessResponseSchema.parse({ok:true,id:requestId,date:timestamp,...appraisal,appraisal,meta:{timestamp,analysis_id:requestId,request_id:requestId,model:GEMINI_MODEL,duration_ms:Date.now()-started,grounding_duration_ms:grounding.durationMs}}); }
export function appraisalErrorResponse(error:unknown,requestId=crypto.randomUUID(),started=Date.now()){const err=error instanceof AppraisalError?error:new AppraisalError('An unexpected appraisal error occurred.','INTERNAL_SERVER_ERROR',500);return{status:err.statusCode,body:{ok:false as const,error:{code:err.code,message:err.message,request_id:requestId,details:err.details},meta:{duration_ms:Date.now()-started}}};}
