import type { ListingComparable, PlatformMarket } from './schema';
import { calculateResellerValuation, robustMarketStats } from './valuation';

const USER_AGENT='Mozilla/5.0 (compatible; PriceSnap/1.1)'; const TIMEOUT_MS=5000;
const STOP=new Set(['the','and','with','for','from','new','used','excellent','good','condition','black','white']);
const BAD=/\b(case|cover|charger|cable|adapter|screen protector|parts?|repair|broken|damaged|box only|manual only|bundle|job lot|replacement)\b/i;
const NEW_ONLY=/\b(brand new|new sealed|factory sealed|unopened)\b/i;
function decode(v:string){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();}
function priceOk(n:number){return Number.isFinite(n)&&n>=5&&n<=100000;}
function host(url:string){try{return new URL(url).hostname.replace(/^www\./,'').toLowerCase();}catch{return'unknown';}}
function tokens(s:string){return new Set(s.toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>1&&!STOP.has(x)));}
function comparable(query:string,title:string){if(!title||BAD.test(title)||NEW_ONLY.test(title))return false;const q=tokens(query),t=tokens(title);if(!q.size)return false;let hits=0;for(const x of q)if(t.has(x))hits++;return hits/q.size>=Math.min(.75, q.size<=2?1:.75);}
function dedupe(xs:ListingComparable[]){const seen=new Set<string>();return xs.filter(x=>{const k=`${x.url.split('?')[0]}|${Math.round(x.priceNzd)}`;if(seen.has(k))return false;seen.add(k);return true;});}
async function html(url:string){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':USER_AGENT,Accept:'text/html','Accept-Language':'en-NZ,en;q=.9'}});return r.ok&&(r.headers.get('content-type')||'').includes('text/html')?await r.text():null;}catch{return null;}finally{clearTimeout(timer);}}
function listing(source:string,title:string,url:string,p:number):ListingComparable{return{source,title:decode(title),url,priceNzd:Math.round(p*100)/100,condition:null,retrievedAt:new Date().toISOString()};}
function parseTradeMe(raw:string,q:string){const out:ListingComparable[]=[];const re=/href="(\/a\/marketplace\/[^"?#]+)"/gi;let m:RegExpExecArray|null;const seen=new Set<string>();while((m=re.exec(raw))&&out.length<25){const path=decode(m[1]);if(seen.has(path))continue;seen.add(path);const chunk=raw.slice(Math.max(0,m.index-1000),m.index+2000);const pm=chunk.match(/(?:NZ\s*\$|NZD\s*|\$)\s*([\d,]+(?:\.\d{1,2})?)/i);const tm=chunk.match(/(?:aria-label|title)="([^"]{3,180})"/i);if(!pm||!tm)continue;const p=Number(pm[1].replace(/,/g,'')),title=decode(tm[1]);if(priceOk(p)&&comparable(q,title))out.push(listing('trademe',title,`https://www.trademe.co.nz${path}`,p));}return out;}
function parseEbay(raw:string,q:string){const out:ListingComparable[]=[];for(const card of(raw.match(/<li[^>]*class="[^"]*s-item[^"]*"[\s\S]*?<\/li>/gi)||[]).slice(0,40)){const tm=card.match(/class="[^"]*s-item__title[^"]*"[^>]*>([\s\S]*?)<\/[^>]+>/i),um=card.match(/class="[^"]*s-item__link[^"]*"[^>]*href="([^"]+)"/i);if(!tm||!um)continue;const title=decode(tm[1]);if(!comparable(q,title))continue;/* Only accept explicitly NZD-denominated eBay prices. Plain '$' is ambiguous and is rejected. */const pm=card.match(/(?:NZ\s*\$|NZD\s*)\s*([\d,]+(?:\.\d{1,2})?)/i);if(!pm)continue;const p=Number(pm[1].replace(/,/g,''));if(priceOk(p))out.push(listing('ebay',title,decode(um[1]),p));}return out;}
async function publicListings(q:string){const[tm,eb]=await Promise.all([html(`https://www.trademe.co.nz/a/marketplace/search?search_string=${encodeURIComponent(q)}`),html(`https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(q)}&_sop=12&LH_ItemCondition=3000`)]);return{trademe:tm?parseTradeMe(tm,q):[],ebay:eb?parseEbay(eb,q):[]};}
async function geminiListings(q:string,warnings:string[]){const key=process.env.GOOGLE_AI_STUDIO_API_KEY||process.env.GEMINI_API_KEY;if(!key)return[];try{const{GoogleGenAI}=await import('@google/genai');const ai=new GoogleGenAI({apiKey:key});const prompt=`Search the web for CURRENT USED listings that are the exact same product as: "${q}". Prioritise New Zealand: Trade Me, Facebook Marketplace pages visible to Google, Cash Converters NZ, used/refurbished retailers, then eBay. Exclude accessories, cases, chargers, parts, broken items, bundles, different generations/models/storage variants, and brand-new retail listings. Return JSON array only: [{"title":"exact listing title","url":"https://...","price":123,"currency":"NZD"}]. IMPORTANT: copy the listing's stated numeric price and currency. Do NOT convert currency and do NOT estimate or infer a missing price. Prefer NZD evidence; non-NZD records may be returned but will be rejected by PriceSnap.`;const r:any=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt,config:{tools:[{googleSearch:{}}]}});const raw=(r.text||'').replace(/```(?:json)?/gi,'').replace(/```/g,'').trim(),a=raw.indexOf('['),b=raw.lastIndexOf(']');if(a<0||b<a)return[];const data=JSON.parse(raw.slice(a,b+1));return(Array.isArray(data)?data:[]).slice(0,20).filter((x:any)=>String(x.currency||'').toUpperCase()==='NZD'&&/^https?:\/\//.test(String(x.url||''))&&priceOk(Number(x.price))&&comparable(q,String(x.title||''))).map((x:any)=>listing(`google_search:${host(String(x.url))}`,String(x.title),String(x.url),Number(x.price)));}catch(e:any){warnings.push(`Gemini grounding unavailable: ${e?.message||e}`);return[];}}
function conf(xs:ListingComparable[]){if(!xs.length)return{score:0,label:'none' as const,evidence_count:0,source_count:0,price_spread:null};const ps=xs.map(x=>x.priceNzd).sort((a,b)=>a-b),med=ps[Math.floor(ps.length/2)],lo=ps[Math.floor((ps.length-1)*.25)],hi=ps[Math.floor((ps.length-1)*.75)],spread=med?(hi-lo)/med:1,sources=new Set(xs.map(x=>host(x.url))).size,score=Math.round((Math.min(1,xs.length/8)*.45+Math.min(1,sources/3)*.25+Math.max(0,1-Math.min(1,spread))*.30)*100)/100;return{score,label:score>=.8?'high' as const:score>=.55?'medium' as const:'low' as const,evidence_count:xs.length,source_count:sources,price_spread:Math.round(spread*100)/100};}
function adjusted(n:number|null,score:number|null,defects:string[]){if(n===null)return null;const cf=score===null?1:.75+(Math.max(1,Math.min(10,score))/10)*.25,df=Math.max(.7,1-Math.min(defects.length,3)*.05);return Math.round(n*cf*df*100)/100;}
export async function groundMarket(itemName:string,conditionScore:number|null=null,defects:string[]=[]){const started=Date.now(),warnings:string[]=[],q=itemName.trim().slice(0,140);const[pub,grounded]=await Promise.all([publicListings(q),geminiListings(q,warnings)]);const facebook=grounded.filter(x=>host(x.url).endsWith('facebook.com'));const all=dedupe([...pub.trademe,...pub.ebay,...grounded]);const tm=robustMarketStats(pub.trademe),eb=robustMarketStats(pub.ebay),fb=robustMarketStats(facebook),combined=robustMarketStats(all);const valuation=calculateResellerValuation([tm,fb,eb,combined]);const recommended=adjusted(valuation.recommendedPrice,conditionScore,defects),low=adjusted(valuation.low,conditionScore,defects),high=adjusted(valuation.high,conditionScore,defects);const accepted=combined?.sample_listings||all,confidence=conf(accepted),sourceCounts=all.reduce<Record<string,number>>((a,x)=>(a[host(x.url)]=(a[host(x.url)]||0)+1,a),{});if(!all.length)warnings.push('No exact comparable NZD listings were found; PriceSnap did not invent a price.');return{market:{trademe:tm,facebook:fb,ebay:eb,trend:null,recommended_price:recommended,price_low:low,price_high:high,best_platform:Object.entries(sourceCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]||null,grounded:all.length>0,confidence,evidence_sources:sourceCounts,sample_listings:accepted,rejected_evidence_count:Math.max(0,pub.trademe.length+pub.ebay.length+grounded.length-accepted.length)},durationMs:Date.now()-started,warnings};}
