import React,{createContext,useContext,useEffect,useState}from'react';
import{AnalysisState,ScanResult,Screen}from'./types';import{triggerHaptic}from'./utils';
interface Ctx{screen:Screen;setScreen:(s:Screen)=>void;direction:number;history:ScanResult[];addToHistory:(r:ScanResult)=>void;currentScan:ScanResult|null;startScan:(i:string)=>Promise<void>;analysisState:AnalysisState;toastMessage:string|null;showToast:(m:string)=>void}
const Context=createContext<Ctx|undefined>(undefined);const KEY='pricesnap.history.v1';
export function AppStateProvider({children}:{children:React.ReactNode}){const[screen,setScreenState]=useState<Screen>('landing');const[direction,setDirection]=useState(1);const[history,setHistory]=useState<ScanResult[]>(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}});const[currentScan,setCurrentScan]=useState<ScanResult|null>(null);const[analysisState,setAnalysisState]=useState<AnalysisState>('idle');const[toastMessage,setToastMessage]=useState<string|null>(null);useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(history.slice(0,50)))}catch{}},[history]);
const setScreen=(n:Screen)=>{const o:Record<Screen,number>={landing:0,home:1,scanner:2,orchestration:3,history:4,settings:5,analyzing:6,result:7,pitch:8,privacy:9};setDirection(o[n]>o[screen]?1:-1);setScreenState(n);triggerHaptic()};
const showToast=(m:string)=>{triggerHaptic();setToastMessage(m);setTimeout(()=>setToastMessage(null),3000)};
const startScan=async(imageBase64:string)=>{triggerHaptic();setAnalysisState('uploading');setScreen('analyzing');try{setAnalysisState('identifying');const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageBase64})});setAnalysisState('grounding');const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||'Analysis failed');setCurrentScan(data as ScanResult);setAnalysisState('complete');setScreen('result')}catch(e:any){console.error(e);setAnalysisState('error');showToast(e?.message||'Error analyzing image. Please try again.');setScreen('scanner')}};
const addToHistory=(r:ScanResult)=>{if(!history.find(h=>h.id===r.id)){setHistory(p=>[r,...p].slice(0,50));showToast('Result saved to history')}else showToast('Already in history')};
return <Context.Provider value={{screen,setScreen,direction,history,addToHistory,currentScan,startScan,analysisState,toastMessage,showToast}}>{children}</Context.Provider>}
export function useAppState(){const c=useContext(Context);if(!c)throw new Error('useAppState must be used within AppStateProvider');return c}
